source=~/.config/hypr/mocha.conf
$SCRIPTS = ~/.config/hypr/scripts

# PROGRAMS - https://wiki.hyprland.org/Configuring/Keywords/
$terminal = kitty
$fileManager = dolphin
$menu = tofi-drun
$runner = wofi --show run
$browser_class = Vivaldi-flatpak

source=./configs/monitors.conf    # Monitor setup
source=./configs/autostart.conf   # Autostart programs on launch of compositer
source=./configs/env.conf         # Enviornment variables set at the launch of the compositer
source=./configs/main.conf        # Main configuration like layout, decoration, animation, misc, xwayland
source=./configs/input.conf       # Any input configuration
source=./configs/gestures.conf    # Trackpad gestures
source=./configs/device.conf      # Any device configuration like mouse or keyboard
source=./configs/groups.conf      # Tab groups configuration
source=./configs/binds.conf       # All system keybinds
source=./configs/rules.conf       # Window, Workspace and Layer rules
source=./configs/plugins.conf     # Hyprland Plugins configuration
