# PER DEVICE CONFIG - https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs
device {
  name = logitech-wireless-mouse-mx-master-2s-1
  sensitivity = -0.8 # Compansate for 2000 dpi
}

device {
  name = elan06fa:00-04f3:327e-touchpad
  disable_while_typing = false
  # drag_3fg = true
  drag_lock = 1
}
