# TRACKPAD GESTURES - https://wiki.hyprland.org/Configuring/Variables/#gestures
gestures {
    # workspace_swipe = true
    # workspace_swipe_fingers = 4
    workspace_swipe_distance = 200
    workspace_swipe_cancel_ratio = 0.2
    workspace_swipe_forever = true
}
gesture = 4, horizontal, workspace
# gesture = 4, up, dispatcher, hyprexpo:expo, enable
# gesture = 4, down, dispatcher, hyprexpo:expo, disable
gesture = 3, pinch, mod: SUPER, float
gesture = 4, swipe, mod: SUPER, move
gesture = 3, swipe, mod: SUPER, resize
gesture = 3, left, dispatcher, layoutmsg, move +col # sendshortcut, CTRL SHIFT, tab, class:^($browser_class)$
gesture = 3, right, dispatcher, layoutmsg, move -col # sendshortcut, CTRL, tab, class:^($browser_class)$
# gesture = 3, left, dispatcher, layoutmsg, move -col
# gesture = 3, right, dispatcher, layoutmsg, move +col

