# GROUP - https://wiki.hypr.land/Configuring/Variables/#group
group {
    drag_into_group = 2
    merge_floated_into_tiled_on_groupbar = true

    col.border_active = $sapphire
    col.border_inactive = $surface2
    col.border_locked_active = $peach
    col.border_locked_inactive = $peach

    groupbar {
        enabled = true
        font_size = 16
        font_weight_active = bold
        height = 24
        gradients = true
        indicator_height = 0
        indicator_gap = 0

        gradient_rounding = 10
        text_offset = 2
        text_color = $text
        text_color_inactive = $subtext0
        col.active = $surface0
        col.inactive = $base
        col.locked_active = $surface0
        col.locked_inactive = $base
        keep_upper_gap = false
      }
}
