# BINDS - https://wiki.hyprland.org/Configuring/Variables/#binds
binds {
    workspace_back_and_forth = true
    hide_special_on_workspace_change = true
    drag_threshold = 30
}

# INPUT - https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = gb
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    numlock_by_default = true

    follow_mouse = 1
    sensitivity = 0.1 # -1.0 - 1.0, 0 means no modification.
    special_fallthrough = true
    emulate_discrete_scroll = 2
    scroll_factor = 1

    touchpad {
        natural_scroll = true
        scroll_factor = 0.7
        # drag_3fg = true
    }
}
