# MONITORS - https://wiki.hyprland.org/Configuring/Monitors/
# Native
monitorv2 {
  output = eDP-1
  mode = preferred
  position = 0x0
  scale = 1.0666667
  bitdepth = 10
  cm = auto
}
# External
monitorv2 {
  output = HDMI-A-1
  mode = 1920x1080@100.00
  position = 0x-1080
  scale = 1
  bitdepth = 10
  cm = auto
}
monitorv2 {
  output = DP-1
  mode = 1920x1080@100.00
  position = 0x-1080
  scale = 1
  bitdepth = 10
  cm = auto
}
monitorv2 {
  output = DP-2
  mode = 1920x1080@100.00
  position = 0x-1080
  scale = 1
  bitdepth = 10
  cm = auto
}
# monitor=DP-1,1920x1080@100.00,0x-1080,1, bitdepth, 10, cm, auto
# monitor=DP-2,1920x1080@100.00,0x-1080,1, bitdepth, 10, cm, auto
