# PLUGINS - https://hypr.land/plugins/
plugin {
    hyprexpo {
        columns = 3
        gap_size = 15
        bg_col = $base
        workspace_method = center r # [center/first] [workspace] e.g. first 1 or center m+1
        skip_empty = true

        enable_gesture = true # laptop touchpad
        gesture_fingers = 4
        gesture_distance = 300 # how far is the "max"
        gesture_positive = false # positive = swipe down. Negative = swipe up.
    }
    hyprscrolling {
        column_width = 0.5
        fullscreen_on_one_column = true
        focus_fit_method = 1
        follow_focus = true
    }
}
