# WINDOW RULES - See https://wiki.hyprland.org/Configuring/Window-Rules/
# Ignore maximize requests from apps
# windowrulev2 = suppressevent maximize, class:.*
# Fix some dragging issues with XWayland
# windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrule = match:pin 1, border_color $peach $yellow
windowrule = keep_aspect_ratio on, match:class scrcpy
windowrule = match:class scrcpy, border_size 0
windowrule = match:class scrcpy, no_shadow 1
windowrule = match:class kitty, xray 1
windowrule = match:class kitty match:floating 1, border_size 0
# windowrule = match:class kitty match:floating 1, no_shadow 1
windowrule = match:title Copying — Dolphin, move 100%-w-20 100%-w-20
windowrule = match:class wofi, border_size 0
windowrule = match:class wofi, no_shadow 1
windowrule = match:initial_title Bitwarden - Vivaldi, float 1
windowrule = match:initial_title Bitwarden - Vivaldi, size 500 700
windowrule = match:initial_title Bitwarden - Vivaldi, move 100%-500 40
windowrule = match:class rmpc, xray 1
windowrule = match:class rmpc, float 1
windowrule = match:class rmpc, border_size 0
windowrule = match:class rmpc, no_shadow 1
windowrule = match:class rmpc, size 75% 70%
# https://amealky.itch.io/teddy-desktop-pet
windowrule = match:class Teddy|MateEngineX.x86_64, border_size 0
windowrule = match:class Teddy|MateEngineX.x86_64, no_shadow 1
windowrule = match:class Teddy|MateEngineX.x86_64, no_blur 1
windowrule = match:class Waydroid, float 1
windowrule = match:class Waydroid, fullscreen 1

windowrule = match:title Friends List, float 1

# Custom control panels
$panels = org.pulseaudio.pavucontrol|blueman-manager
windowrule = match:class $panels, float 1
windowrule = match:class $panels, border_size 0
windowrule = match:class $panels, size 650 550
windowrule = match:class $panels, move monitor_w-650-15 63

windowrule = match:class xwaylandvideobridge, opacity 0.0 override
windowrule = match:class xwaylandvideobridge, no_anim 1
windowrule = match:class xwaylandvideobridge, no_initial_focus 1
windowrule = match:class xwaylandvideobridge, max_size 1 1
windowrule = match:class xwaylandvideobridge, no_blur 1
windowrule = match:class xwaylandvideobridge, no_focus 1

# WORKSPACE RULES - https://wiki.hyprland.org/Configuring/Workspace-Rules/

# LAYER RULES - https://wiki.hypr.land/Configuring/Window-Rules/#layer-rules
layerrule = match:namespace waybar, ignore_alpha 0, blur 1
layerrule = match:namespace notifications, ignore_alpha 0, blur 1
layerrule = match:namespace nwg-dock, ignore_alpha 0, blur 1
layerrule = match:namespace wofi, ignore_alpha 0, blur 1
layerrule = match:namespace launcher, ignore_alpha 0, blur 1
layerrule = match:namespace top, ignore_alpha 0, blur 1
layerrule = match:namespace logout_dialog, blur 1
layerrule = match:namespace resolution-settings, ignore_alpha 0, blur 1
layerrule = match:namespace brightness-settings, ignore_alpha 0, blur 1
layerrule = match:namespace monitor-settings, ignore_alpha 0, blur 1
layerrule = match:namespace system-menu, ignore_alpha 0, blur 1
layerrule = match:namespace notification-center, ignore_alpha 0, blur 1
layerrule = match:namespace music-center, ignore_alpha 0, blur 1
