# WINDOW RULES - See https://wiki.hyprland.org/Configuring/Window-Rules/
# Ignore maximize requests from apps
windowrulev2 = suppressevent maximize, class:.*
# Fix some dragging issues with XWayland
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
windowrulev2 = bordercolor $peach $yellow,pinned:1
windowrule = scrollmouse 0.033, class:mcpelauncher-client
windowrule = keepaspectratio on, class:^(scrcpy)$
windowrule = noborder 1, class:^(scrcpy)$
windowrule = noshadow 1, class:^(scrcpy)$
windowrule = xray, class:^(kitty)$
windowrule = noborder 1, class:^(kitty)$ floating:1
# windowrule = noshadow 1, class:^(kitty)$ floating:1
windowrule = move 100%-w-20 100%-w-20, title:^(Copying — Dolphin)$
windowrule = noborder 1, class:^(wofi)$
windowrule = noshadow 1, class:^(wofi)$
windowrule = float, initialTitle:^(Bitwarden - Vivaldi)$
windowrule = size 500 700, initialTitle:^(Bitwarden - Vivaldi)$
windowrule = move 100%-500 40, initialTitle:^(Bitwarden - Vivaldi)$
windowrule = xray, class:^(rmpc)$
windowrule = float, class:^(rmpc)$
windowrule = noborder 1, class:^(rmpc)$
windowrule = noshadow 1, class:^(rmpc)$
windowrulev2 = size 75% 70%, class:^(rmpc)$
# https://amealky.itch.io/teddy-desktop-pet
windowrule = noborder 1, class:^(Teddy|MateEngineX.x86_64)$
windowrule = noshadow 1, class:^(Teddy|MateEngineX.x86_64)$
windowrule = noblur 1, class:^(Teddy|MateEngineX.x86_64)$
windowrule = float, class:^(Waydroid)$
windowrule = fullscreen, class:^(Waydroid)$

windowrule = float, title:^(Friends List)$

# Custom control panels
$panels = org.pulseaudio.pavucontrol|blueman-manager
windowrule = float, class:^($panels)$
windowrule = noborder 1, class:^($panels)$
windowrulev2 = move 100%-w-15 63, class:^($panels)$
windowrulev2 = size 650 550, class:^($panels)$

windowrule = opacity 0.0 override, class:^(xwaylandvideobridge)$
windowrule = noanim, class:^(xwaylandvideobridge)$
windowrule = noinitialfocus, class:^(xwaylandvideobridge)$
windowrule = maxsize 1 1, class:^(xwaylandvideobridge)$
windowrule = noblur, class:^(xwaylandvideobridge)$
windowrule = nofocus, class:^(xwaylandvideobridge)$

# WORKSPACE RULES - https://wiki.hyprland.org/Configuring/Workspace-Rules/

# LAYER RULES - https://wiki.hypr.land/Configuring/Window-Rules/#layer-rules
layerrule = blur,waybar
layerrule = ignorealpha,waybar$
layerrule = blur,notifications
layerrule = ignorealpha,notifications$
layerrule = blur,nwg-dock
layerrule = ignorealpha,nwg-dock$
layerrule = blur,wofi
layerrule = ignorealpha,wofi$
layerrule = blur,launcher
layerrule = ignorealpha,launcher$
layerrule = blur,top$
layerrule = ignorealpha,top$
layerrule = blur,logout_dialog
layerrule = blur,resolution-settings$
layerrule = ignorealpha,resolution-settings$
layerrule = blur,brightness-settings$
layerrule = ignorealpha,brightness-settings$
layerrule = blur,monitor-settings$
layerrule = ignorealpha,monitor-settings$
layerrule = blur,system-menu$
layerrule = ignorealpha,system-menu$
layerrule = blur,dunst-center$
